name: Deploy to Server

on:
  push:
    branches:
      - main  # O la rama que prefieras para el deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@168.231.82.135 << 'EOF'
          cd /opt/entertainment-web-app
          git pull origin main
          npm install
          npm run build
          rm -rf /var/www/wickeddev_es_usr/data/www/entertainment-wep-app.wickeddev.es/*
          cp -r build/* /var/www/wickeddev_es_usr/data/www/entertainment-wep-app.wickeddev.es/
        EOF
