name: Deploy to Server

on:
  push:
    branches:
      - main  # O la rama que prefieras para el deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no root@168.231.82.135 << 'EOF'
          set -e  # Para que falle si algo falla
          
          # Cambiar a la carpeta donde está el repositorio
          cd /opt/entertainment-web-app  

          # Actualizar el repositorio con los cambios más recientes
          echo "Actualizando código..."
          git pull origin main

          # Instalar las dependencias necesarias
          echo "Instalando dependencias..."
          npm install

          # Construir la aplicación
          echo "Construyendo la app..."
          npm run build

          # Limpiar el directorio de destino
          echo "Limpiando directorio destino..."
          rm -rf /var/www/wickeddev_es_usr/data/www/entertainment-wep-app.wickeddev.es/*

          # Copiar los archivos del build al directorio de producción
          echo "Copiando build..."
          cp -r build/* /var/www/wickeddev_es_usr/data/www/entertainment-wep-app.wickeddev.es/

          # Confirmación del deploy
          echo "¡Deploy completado!"
        EOF
